services:
  dbuggen2:
    build:
      context: .
      target: builder
    ports: [ "3000:3000" ]
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://dbuggen2:dbuggen2@db/dbuggen2?sslmode=disable
      - DFUNKT_URL=https://dfunkt.datasektionen.se
      - DARKMODE_URL=https://darkmode.datasektionen.se
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
    command: ["go", "run", "."]
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=dbuggen2
      - POSTGRES_USER=dbuggen2
      - POSTGRES_DB=dbuggen2
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d dbuggen2 -U dbuggen2'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
